# Generated by Django 5.2.7 on 2025-12-04 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='idCategoria',
            field=models.AutoField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='fechaEntrada',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
