# Generated by Django 5.2.7 on 2025-12-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_categoria_idcategoria_alter_categoria_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='state',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='lote',
            old_name='state',
            new_name='disponible',
        ),
        migrations.AddField(
            model_name='categoria',
            name='stock_actual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lote',
            name='n_serie',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='idCategoria',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lote',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
