# Generated by Django 5.2.7 on 2025-12-06 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_rename_state_categoria_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
