# Generated by Django 5.2.7 on 2025-12-06 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_producto_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='stock_actual',
            new_name='productos_disponibles',
        ),
        migrations.RenameField(
            model_name='lote',
            old_name='precio',
            new_name='precio_compra',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='state',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='precio_venta',
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_transaccion', models.CharField(max_length=30)),
                ('fecha_transaccion', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('REAJUSTE', 'Reajuste')], max_length=10)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Transacciones', to='catalogo.lote')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('lote', 'usuario', 'id_transaccion')},
            },
        ),
    ]
