# Generated by Django 5.2.7 on 2025-12-06 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_rename_stock_actual_categoria_productos_disponibles_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Transaccion', to='catalogo.lote'),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaccion', to=settings.AUTH_USER_MODEL),
        ),
    ]
