# Generated by Django 5.2.7 on 2025-12-06 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_remove_producto_stock_alter_transacciones_lote_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transacciones',
        ),
    ]
