# Generated by Django 5.2.7 on 2025-12-11 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_delete_transacciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='productos_disponibles',
        ),
    ]
