# Generated by Django 5.2.7 on 2025-12-11 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_remove_categoria_productos_disponibles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='catalogo.producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idCategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.categoria'),
        ),
    ]
