# Generated by Django 5.2.7 on 2025-11-12 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='rutID',
            new_name='rut',
        ),
    ]
