# Generated by Django 5.2.7 on 2025-12-10 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0007_delete_transacciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_transaccion', models.CharField(max_length=30, unique=True)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE_POST', 'Ajuste Positivo'), ('AJUSTE_NEG', 'Ajuste Negativo')], max_length=15)),
                ('cantidad', models.PositiveBigIntegerField(default=1)),
                ('motivo', models.CharField(blank=True, max_length=50, null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='catalogo.lote')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_transaccion'],
            },
        ),
    ]
