# Generated by Django 5.2.7 on 2025-12-11 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='id_transaccion',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
        migrations.CreateModel(
            name='OperacionInventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(help_text='Código de la operación (ej: OP-20251210-0001).', max_length=40, unique=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('documento_referencia', models.CharField(blank=True, help_text='OC, guía de despacho, factura, etc.', max_length=50, null=True)),
                ('motivo_general', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='transaccion',
            name='operacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='operaciones.operacioninventario'),
            preserve_default=False,
        ),
    ]
