# Generated by Django 5.2.7 on 2025-12-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_alter_transaccion_id_transaccion_operacioninventario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacioninventario',
            name='documento_referencia',
            field=models.CharField(blank=True, help_text='OC, guía de despacho, factura, etc.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operacioninventario',
            name='motivo_general',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='motivo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
